# Generated by Django 3.2.9 on 2022-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_historicaluser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
