# Generated by Django 3.2.9 on 2022-01-03 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discount',
            name='end_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
