# Generated by Django 3.2.9 on 2022-01-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220103_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='end_start',
            new_name='date_end',
        ),
    ]
