# Generated by Django 3.2.9 on 2021-12-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('item', '0001_initial'),
        ('inventory_management', '0002_alter_dailyreceipthistorydetail_daily_receipt_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyReceiptHistory',
            new_name='DailyReceipt',
        ),
        migrations.RenameModel(
            old_name='DailyReceiptHistoryDetail',
            new_name='DailyReceiptDetail',
        ),
    ]
