# Generated by Django 3.2.9 on 2021-12-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_auto_20211229_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreceiptdetail',
            old_name='daily_receipt_history',
            new_name='daily_receipt',
        ),
        migrations.AlterModelTable(
            name='dailyreceipt',
            table='daily_receipt_tbl',
        ),
        migrations.AlterModelTable(
            name='dailyreceiptdetail',
            table='daily_receipt_detail_tbl',
        ),
    ]
