# Generated by Django 3.2.9 on 2021-12-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_auto_20211229_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreceiptdetail',
            name='daily_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_receipts', to='inventory_management.dailyreceipt'),
        ),
    ]
